(function() {var implementors = {};
implementors["simple_net"] = [{text:"impl&lt;Func, Derivative&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"simple_net/struct.Activation.html\" title=\"struct simple_net::Activation\">Activation</a>&lt;Func, Derivative&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;Derivative: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a>,<br>&nbsp;&nbsp;&nbsp;&nbsp;Func: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a>,&nbsp;</span>",synthetic:true,types:["simple_net::layers::Activation"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"simple_net/struct.Linear.html\" title=\"struct simple_net::Linear\">Linear</a>",synthetic:true,types:["simple_net::layers::Linear"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"simple_net/struct.MeanSquared.html\" title=\"struct simple_net::MeanSquared\">MeanSquared</a>",synthetic:true,types:["simple_net::loss::MeanSquared"]},{text:"impl !<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"simple_net/struct.NeuralNet.html\" title=\"struct simple_net::NeuralNet\">NeuralNet</a>",synthetic:true,types:["simple_net::net::NeuralNet"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"simple_net/struct.Tensor.html\" title=\"struct simple_net::Tensor\">Tensor</a>",synthetic:true,types:["simple_net::tensor::Tensor"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
